Switch to appuser to avoid root (#43)
* Switch to appuser for pip install

---------

Signed-off-by: Benoit Donneaux <benoit@leastauthority.com>

diff --git a/relay/Dockerfile b/relay/Dockerfile
--- a/relay/Dockerfile
+++ b/relay/Dockerfile
@@ -19,6 +19,31 @@ RUN pip install \
     --upgrade \
     -r /app/requirements.txt
 
+# Parameters for default user:group
+ARG uid=1000
+ARG user=appuser
+ARG gid=1000
+ARG group=appgroup
+
+# Add group and user so the command above and its
+# output will be owned by the specified uid:gid
+# These steps will fail explicitely on conflict
+RUN getent group "${gid}" > /dev/null \
+    || groupadd -g "${gid}" "${group}"; \
+    test "$(getent group "${gid}")" = "$(getent group "${group}")" \
+    || { echo "Group name/id conflict!"; exit 1; }
+RUN id "${uid}" > /dev/null 2>&1 \
+    || useradd -md "/home/${user}" -s /bin/bash -g "${group}" -u "${uid}" "${user}"; \
+    test "$(id "${uid}")" = "$(id "${user}")" \
+    || { echo "User name/id conflict!"; exit 1; }
+
+# Prepare directories with ownership
+RUN { test -d /db || mkdir /db; } && chown -R ${user}:${group} /db
+
+# Switch to non-root user
+USER ${user}
+WORKDIR /app
+
 # Default parameters and command to start
 ENV MW_RELAY_BLUR_USAGE="3600"
 ENV MW_RELAY_PROTO="tcp"
